# Generated by Django 4.2.10 on 2024-03-03 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='publish_date',
            new_name='publish',
        ),
    ]
